apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: USERNAME2
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: key2
