apiVersion: v1
kind: Pod
metadata:
  name: http-get-liveness-pod
spec:
  containers:
  - name: http-get-container
    image: venuzs/my-http-app:latest
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
