apiVersion: v1
kind: Pod
metadata:
  name: tcp-socket-liveness-pod
spec:
  containers:
  - name: tcp-socket-container
    image: venuzs/my-http-app:v1
    ports:
    - containerPort: 5050
    livenessProbe:
      tcpSocket:
        port: 5050
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
