apiVersion: v1
kind: Pod
metadata:
  name: exec-readiness-example
spec:
  containers:
  - name: example-container
    image: venuzs/my-http-app:latest
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - 'nc -z localhost 8080'
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
