apiVersion: v1
kind: Pod
metadata:
  name: tcp-readiness-example
spec:
  containers:
  - name: example-container
    image: venuzs/my-http-app:latest
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
