apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcg==  # base64-encoded value for 'user'
  password: cGFzc3dvcmQ=  # base64-encoded value for 'password'
