apiVersion: v1
kind: Pod
metadata:
  name: myapp111
  labels:
    name: myapp111
spec:
  containers:
  - name: nginx111
    image: nginx
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - backend
        weight: 1
