apiVersion: v1
kind: Pod
metadata:
  name: myapp11
  labels:
    name: myapp11
spec:
  containers:
  - name: nginx11
    image: nginx
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: name
            operator: In
            values:
            - venu
