apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0  # Specify the Kubernetes version here
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
  - role: worker
    image: kindest/node:v1.30.0
  - role: worker
    image: kindest/node:v1.30.0
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16